src/apps/everest_user/urls.py
"""URL's for esf_us forms."""

from django.conf.urls import url
from .views import everest_login, everest_logout


urlpatterns = [
    url(r'^login/$', view=everest_login, name='login'),
    url(r'^logout/$', view=everest_logout, name='logout'),
]

src/apps/home/urls.py
from django.conf.urls import url
from .views import home


urlpatterns = [
    url(r'^$', view=home, name='index'),
]

src/everest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^user/', include('apps.everest_user.urls', namespace='user')),
    url(r'^admin/', admin.site.urls),
]

src/apps/deal_tool/models.py
from django.db import models
from django.conf import settings
import json


class DealStatusEnum(object):
    PENDING = 1
    PARTIALLY_APPROVED = 2
    APPROVED = 3


DEAL_STATUS_CHOICES = [
    [DealStatusEnum.PENDING, "Pending"],
    [DealStatusEnum.PARTIALLY_APPROVED, "Partially Approved"],
    [DealStatusEnum.APPROVED, "Approved"]
]


class Deal(models.Model):
    """Model to store Sales Force Deal info."""

    name = models.CharField(max_length=255)
    account = models.CharField(max_length=255, blank=True, null=True)
    probability = models.FloatField(blank=True, null=True)
    project_id = models.CharField(max_length=255, unique=True, primary_key=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    staff_owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='staff_owner')
    pod = models.CharField(max_length=255, blank=True, null=True)
    staff_manager = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='staff_manager')
    status = models.IntegerField(choices=DEAL_STATUS_CHOICES, blank=False, null=False, default=DEAL_STATUS_CHOICES[0][1])
    revenue = models.FloatField(blank=True, null=True)
    contract_hours = models.FloatField(blank=True, null=True)
    last_modified_date = models.DateField(auto_now=True)

    @classmethod
    def list_deals_in_json(cls):
        return json.dumps([str(x) for x in cls.objects.all()])

    def __str__(self):
        return "%s | %s | %s" % (self.project_id, self.account, self.name)

src/apps/everest_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserRoleEnum(object):
    STAFFING_OWNER = 1
    STAFFING_MANAGER = 2
    FINANCIAL_OWNER = 3


ROLE_CHOICES = [
    [UserRoleEnum.STAFFING_OWNER, 'Staffing Owner'],
    [UserRoleEnum.STAFFING_MANAGER, 'Staffing Manager'],
    [UserRoleEnum.FINANCIAL_OWNER, 'Sales Associate'],
]


class User(AbstractUser):
    username = models.EmailField(max_length=255, blank=False, null=False, unique=True,
                                 verbose_name='Email ID')
    role = models.IntegerField(choices=ROLE_CHOICES, blank=False, null=True)
    temporary_password = models.CharField(max_length=120, blank=True, null=True)
    phone_number = models.CharField(max_length=25, blank=True, null=True,)
    needs_password_change = models.BooleanField(default=True, help_text='If selected user will be forced to change'
                                                                        ' their password when they login',
                                                verbose_name='Force password change')

src/apps/home/models.py
from django.db import models

# Create your models here.

src/apps/everest_user/forms.py
from django import forms


class LoginForm(forms.Form):
    email_id = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'email'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

src/apps/deal_tool/views.py
from django.shortcuts import render

# Create your views here.

src/apps/everest_user/views.py
import random
from django.shortcuts import render
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import get_user_model

User = get_user_model()


def everest_login(request):
    if request.method == "GET":
        login_form = LoginForm()
    elif request.method == "POST":
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get("email_id", None)
            password = login_form.cleaned_data.get("password", None)
            user_from_db = User.objects.get(username__iexact=username)
            user = authenticate(username=user_from_db.username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse_lazy('home:index'))
        return HttpResponseRedirect(reverse_lazy('user:login'))

    context = {
        "image_pick": random.choice([x for x in range(1, 7)]),
        "login_form": login_form,
    }
    return render(request, "everest_user/login.html", context)


def everest_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('user:login'))

src/apps/home/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from apps.deal_tool.models import Deal


@login_required(login_url=reverse_lazy('user:login'))
def home(request):
    context = {
        "data": Deal.list_deals_in_json()
    }
    return render(request, "home/home.html", context)

src/apps/everest_user/templates/everest_user/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
<div class="login-container">
    <div id="output"></div>
        <div class="avatar">Welcome to Everest!</div>
        <div class="form-box">
            <form action="" method="POST">
                {% csrf_token %}
                {{login_form.email_id}}
                {{login_form.password}}
                <button class="btn btn-info btn-block login" type="submit">Login</button>
            </form>
            <a href="">Forgot your password?</a>
        </div>
</div>
{% endblock body %}
{% block css %}
    <style type="text/css">
        body{
            background: url("/static/img/{{image_pick}}.jpg");
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css%}

src/apps/home/templates/home/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Everest Deal Tool</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'user:logout' %}"><span class="glyphicon glyphicon-log-in"></span> logout</a></li>
        </ul>
    </div>
</nav>
{% endblock header%}

{% block body %}
    <h1 class="home_text" >Hello {{request.user.get_full_name }}!</h1>
    <div class="container-fluid project-lookup-container">
        <div class="row">
            <div class="col-md-2 home_text">
                Project ID
            </div>
            <div class="ui-widget custom_autocomplete">
                <input id="tags">
            </div>
        </div>
        {{data}}
    </div>
{% endblock body %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/home.js' %}"></script>
{% endblock js%}

{% block css %}
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
{% endblock css%}

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>GALE Everest</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="shortcut icon" type="image/png" href="https://www.galepartners.com/static/imgs/gale-favicon.png">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        {% block js %} {% endblock js %}
        {% block css %} {% endblock css %}
        {% block extrahead %} {% endblock extrahead %}
    </head>
    <body>
        {% block header %} {% endblock header%}
        <div class="container">
            {% block body %} {% endblock body %}
        </div>
        {% block footer %} {% endblock footer%}
    </body>
</html>